CREATE TABLE airplane (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    model_number VARCHAR(255) NOT NULL,
    capacity BIGINT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
